movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls'))
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
  path('', views.index, name='index'),
  path('board/', views.board, name='board'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name="detail"),
  path('<int:pk>/delete/', views.delete, name="delete"),
  path('<int:pk>/update/', views.update, name="update"),
]

reviews/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Review(models.Model):
  title = models.CharField(max_length=100)
  content = models.TextField()
  movie_name = models.CharField(max_length=100)
  grade = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"
        widgets = {
            "title" : forms.TextInput(
                attrs= {
                    "class" : "form-control"
                },
            ),
            "grade" : forms.NumberInput(
                attrs= {
                    "class" : "form-control",
                    "placeholder" : "0 ~ 5",
                },
            ),
        }
        
        labels = {
            "title" : "제목",
            "content": "내용",
            "movie_name" : "영화 제목",
            "grade" : "점수"
        }

reviews/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm

# Create your views here.

# index 페이지

def index(request):
  return render(request, 'reviews/index.html')


def board(request):
  context = {
    'reviews' : Review.objects.all().order_by('-created_at'),
  }
  return render(request, 'reviews/board.html', context)

def create(request):
  if request.method == "POST":
    review_form = ReviewForm(request.POST)
    if review_form.is_valid():
      review_form.save()
      return redirect("reviews:board")
  else:
    review_form = ReviewForm()
  context = {
    "review_form" : review_form
  }
  return render(request, 'reviews/create.html', context)

def update(request, pk):
  review = Review.objects.get(pk=pk)
  if request.method == "POST":
    review_form = ReviewForm(request.POST, instance=review)
    if review_form.is_valid():
      review_form.save()
      return redirect("reviews:board")
  else:
    review_form = ReviewForm(instance=review)
  context = {
    "review_form" : review_form,
    "num" : review.pk
  }
  return render(request, 'reviews/update.html', context)

def detail(request, pk):
  context = {
    "review": Review.objects.get(pk=pk),
  }
  return render(request, 'reviews/detail.html', context)

def delete(request, pk):
  review = Review.objects.get(pk=pk)
  review.delete()
  return redirect("reviews:board")

reviews/templates/reviews/board.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MOVIE | BOARD{% endblock title %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block content %}
  <main>
    <section class="extrabg">
      <div class="board container">
        <h1 class="text-center pb-3">영화 리뷰 목록</h1>
        <a role="button" class="btn btn-secondary" href="{% url 'reviews:create' %}">작성</a>
        <div class="review-table">
          <table class="table container">
            <thead>
              <tr>
                <th scope="col">리뷰 제목</th>
                <th scope="col">영화 제목</th>
                <th scope="col">내용 보기</th>
              </tr>
            </thead>
            <tbody>
              {% for review in reviews %}
                <tr>
                  <td>
                    <a class="board-review-title" href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
                  </td>
                  <td>{{ review.movie_name }}</td>
                  <td>
                    <a role="button" class="btn btn-outline-secondary btn-sm" href="{% url 'reviews:detail' review.pk %}">내용보기</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  </main>
{% endblock content %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}MOVIE | NEW{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
  <main>
    <section class="extrabg">
      <div class="create container">
        <h1 class="text-center">
          리뷰 작성
        </h1>
        <div class="container">
          <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form review_form %}
            <button type="submit" class="btn btn-dark form-control">등록</button>
          </form>
        </div>
      </div>
    </section>
  </main>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}MOVIE |
  {{ review.title }}
{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock css %}

{% block content %}
  <main>
    <section class="extrabg">
      <div class="detail-review container">
        <!-- 게시글 -->
        <div class="review p-5">
          <h1>
            <p>{{ review.title }}</p>
          </h1>
          <h4 class="py-3">{{ review.movie_name }}
            <span class="grade">| 평점:
              {{ review.grade }}</span></h4>
          <p class="time pb-3">작성:
            {{ review.created_at }}
            | 수정:
            {{ review.updated_at }}</p>
          <h3 class="pb-4">{{ review.content }}</h3>
        </div>
        <!-- 수정삭제 버튼 -->
        <div class="p-5">
          <a role="button" class="btn btn-outline-secondary" href="{% url 'reviews:update' review.pk %}">수정</a>
          <a href="{% url 'reviews:delete' review.pk %}" type="button" class="btn btn-danger">삭제</a>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MOVIE{% endblock title %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">{% endblock css %}

{% block content %}
  <main>
    <a href="{% url 'reviews:board' %}">
      <section class="homepage"></section>
    </a>
  </main>
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}MOVIE |
  {{ review.title }}
{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
  <main>
    <section class="extrabg">
      <div class="create container">
        <h1 class="text-center py-3">
          리뷰 수정
        </h1>
        <div class="container">
          <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form review_form %}
            <button type="submit" class="btn btn-secondary">수정</button>
            <a role="button" class="btn btn-dark" href="{% url 'reviews:detail' num %}">뒤로가기</a>
          </form>
        </div>
      </div>
    </section>
  </main>
{% endblock %}